CC=pdflatex

maketable:
	$(CC) TABLE.tex
	$(CC) TABLE.tex
	#bibtex TABLE
	#$(CC) TABLE.tex
	#$(CC) TABLE.tex

cleantable:
	rm *.aux *.log *.blg *.bbl *.out

cleartable:
	rm *.aux *.log *.blg *.bbl *.out *.pdf 

